name: mtg

services:
  # TODO: separate out database service into separate compose file
  db:
    user: $DOCKER_USER
    image: postgres:16
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5497:5432"
    volumes:
      - ./data/db/mtg/postgres/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - mtg

  api:
    user: $DOCKER_USER
    build:
      context: src
      dockerfile: Dockerfile
      args:
        DOCKER_USER: $DOCKER_USER
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./data:/opt/mtg/data
      - /opt/mtg/data/db/
      - ./src:/code
      - ./scripts:/opt/mtg/scripts
    ports:
      - "8998:8000"
    env_file: .env
    environment:
      - DATA_DIR=/opt/mtg/data
    networks:
      - mtg

  api-test:
    user: $DOCKER_USER
    profiles:
      - test
    # better to extend _api or just use different defs?
    build:
      context: src
      dockerfile: Dockerfile
    working_dir: /
    command: pytest --color=yes -vv
    volumes:
      - ./src:/code
      - ./test:/test
      - ./pytest.ini:/pytest.ini
    env_file: .env
    networks:
      - mtg

  # TODO: implement [angular|react] front-end
  # _web:
  #   build:
  #     context: web
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./web:/app
  #   ports:
  #     - "8089:80"
  #   networks:
  #     - microservices

networks:
  mtg:
    name: mtg
